# Generated by Django 5.0.4 on 2024-05-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
                ('menu', models.TextField()),
                ('min_guests', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CateringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DecorationsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureSupplyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('min_guests', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('passport_details', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('location', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('themed_party', 'Themed Party'), ('graduation', 'Graduation')], max_length=20)),
                ('theme', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('catering_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.cateringcompany')),
                ('cleaning_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.cleaningcompany')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.client')),
                ('decorations_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.decorationscompany')),
                ('entertainment_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.entertainmentcompany')),
                ('furniture_company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.furnituresupplycompany')),
                ('suppliers', models.ManyToManyField(default='', to='events.supplier')),
                ('venue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
