# Generated by Django 4.2.10 on 2024-05-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_catering_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(default='', null=True, related_name='events', to='events.guest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.TimeField(),
        ),
    ]
