# Generated by Django 4.2.10 on 2024-05-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
    ]
