# Generated by Django 4.2.10 on 2024-05-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='events', to='events.guest'),
        ),
    ]
